services:
  engknowledgegraph-neo4j:
    image: neo4j:5
    container_name: engknowledgegraph-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
   
    restart: unless-stopped

  engknowledgegraph-watcher:
    build: .
    container_name: engknowledgegraph-watcher
    depends_on:
      - engknowledgegraph-neo4j
    volumes:
      - ./data:/app/data
    environment:
      NEO4J_URI: bolt://engknowledgegraph-neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    restart: unless-stopped

  engknowledgegraph-ui:
    build:
      context: .
      dockerfile: chat/Dockerfile 
    container_name: engknowledgegraph-ui
    ports:
      - "8501:8501"
    depends_on:
      - engknowledgegraph-watcher
    restart: unless-stopped
  engknowledgegraph-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: engknowledgegraph-backend
    ports:
      - "8000:8000"
    depends_on:
      - engknowledgegraph-neo4j
    environment:
      NEO4J_URI: bolt://engknowledgegraph-neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    restart: unless-stopped

volumes: 
  neo4j_data: 
  neo4j_logs: